version: "3.8"
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    build: .
    networks:
      - db_network
      - web_network
    volumes:
      - D:/vietthanh/fullStack/vietthanh-dashboard/django-api/dataDB:/app # mount thư mục host /dataDB vào /app trong container
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5000:5000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - appseed-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
