# Generated by Django 3.2.13 on 2025-05-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_authentication', '0003_aanhanvien'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AANhanVien',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
