# Generated by Django 3.2.13 on 2025-04-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
