# Generated by Django 3.2.13 on 2025-04-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAbdstinhthanh',
            fields=[
                ('Matinh', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Tentinh', models.CharField(max_length=50)),
                ('Danso', models.IntegerField()),
                ('Ngaytao', models.DateTimeField()),
                ('Usertao', models.CharField(max_length=50)),
                ('Dientichkm', models.IntegerField()),
                ('Sohuyen', models.IntegerField()),
                ('Sokilometvc', models.IntegerField()),
                ('kSD', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AAcdshuyen',
            fields=[
                ('Mahuyen', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Tenhuyen', models.CharField(max_length=50)),
                ('Danso', models.IntegerField()),
                ('Dientichkm', models.IntegerField()),
                ('Soxa', models.IntegerField()),
                ('Sokilometvc', models.IntegerField()),
                ('Ngaytao', models.DateTimeField()),
                ('Usertao', models.CharField(max_length=50)),
                ('Matinh', models.CharField(max_length=50)),
                ('ksd', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AAcdsxuyen',
            fields=[
                ('Maxa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Tenxa', models.CharField(max_length=50)),
                ('Danso', models.IntegerField()),
                ('Dientichkm', models.IntegerField()),
                ('Socho', models.IntegerField()),
                ('Sokilometvc', models.IntegerField()),
                ('Ngaytao', models.DateTimeField()),
                ('Usertao', models.CharField(max_length=50)),
                ('Mahuyen', models.CharField(max_length=50)),
                ('Ksd', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AAddskhach',
            fields=[
                ('Makhach', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Tenkhach', models.CharField(max_length=50)),
                ('Sodienthoai', models.IntegerField()),
                ('Ngaytao', models.DateTimeField()),
                ('User', models.CharField(max_length=50)),
                ('Pass', models.CharField(max_length=50)),
                ('Danghi', models.BooleanField()),
                ('Hinhanh', models.BinaryField(null=True)),
                ('Xem', models.BooleanField()),
                ('Sua', models.BooleanField()),
                ('Xoa', models.BooleanField()),
                ('Them', models.BooleanField()),
                ('Ngayvinhhat', models.DateTimeField()),
                ('Diachi', models.CharField(max_length=250)),
                ('Loaiinhinh', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Sdtzalo', models.CharField(max_length=50)),
                ('Nguoilienhe', models.CharField(max_length=50)),
                ('Xaphuong', models.CharField(max_length=50)),
                ('Ksd', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AAddsqutang',
            fields=[
                ('Mamonqua', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Tenmonqua', models.CharField(max_length=50)),
                ('Ngaytao', models.DateTimeField()),
                ('Giatri', models.IntegerField()),
                ('Hinhanh', models.BinaryField(null=True)),
                ('Doanhsosapdung', models.CharField(max_length=50)),
                ('Ghichu', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aadsvitri',
            fields=[
                ('LoaiID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Loaiten', models.CharField(max_length=50)),
                ('Ngay', models.DateTimeField()),
                ('Userlap', models.CharField(max_length=50)),
                ('Ksd', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CAadonvinh',
            fields=[
                ('Madvt', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Tendvt', models.CharField(max_length=50)),
                ('Ngaytao', models.DateTimeField()),
                ('Usertao', models.CharField(max_length=50)),
                ('Ksd', models.BooleanField()),
                ('Ghichu', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='F_AadahnSachHD',
            fields=[
                ('Sobienban', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Ngaybb', models.DateTimeField()),
                ('Userlap', models.CharField(max_length=50)),
                ('Mamonqua', models.CharField(max_length=50)),
                ('Apdungtungay', models.DateTimeField()),
                ('Tyleckhong', models.IntegerField()),
                ('Dsdangky', models.IntegerField()),
                ('Congnoapdung', models.IntegerField()),
                ('Diengiai', models.CharField(max_length=250)),
                ('Duyet', models.BooleanField()),
                ('Ngayduyet', models.DateTimeField()),
                ('Ghichu', models.TextField(null=True)),
                ('Loaihd', models.CharField(max_length=50)),
                ('Ngayketthuc', models.DateTimeField()),
                ('Makhachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_banhang.aaddskhach')),
            ],
        ),
        migrations.CreateModel(
            name='Abdsnhanvien',
            fields=[
                ('Manhanvien', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Tennhanvien', models.CharField(max_length=50)),
                ('Sodienthoai', models.IntegerField()),
                ('NgayvaoLam', models.DateTimeField()),
                ('User', models.CharField(max_length=50)),
                ('Pass', models.CharField(max_length=50)),
                ('Danghiviec', models.BooleanField()),
                ('Hinhanh', models.BinaryField(null=True)),
                ('Xem', models.BooleanField()),
                ('Sua', models.BooleanField()),
                ('Xoa', models.BooleanField()),
                ('Them', models.BooleanField()),
                ('Ksd', models.BooleanField()),
                ('MaNPP', models.CharField(max_length=50)),
                ('LoaiID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_banhang.aadsvitri')),
            ],
        ),
        migrations.CreateModel(
            name='AAkhaibaonv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maadmin', models.CharField(max_length=50)),
                ('Maquanly', models.CharField(max_length=50)),
                ('Ngaytao', models.DateTimeField()),
                ('Manhanvien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_banhang.abdsnhanvien')),
            ],
        ),
        migrations.AddField(
            model_name='aaddskhach',
            name='LoaiID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_banhang.aadsvitri'),
        ),
        migrations.AddField(
            model_name='aaddskhach',
            name='Nhanvien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_banhang.abdsnhanvien'),
        ),
    ]
