# Generated by Django 3.2.13 on 2025-04-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_banhang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAcdsxa',
            fields=[
                ('Maxa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Tenxa', models.CharField(max_length=50)),
                ('Danso', models.IntegerField()),
                ('Dientichkm', models.IntegerField()),
                ('Socho', models.IntegerField()),
                ('Sokilometvc', models.IntegerField()),
                ('Ngaytao', models.DateTimeField()),
                ('Usertao', models.CharField(max_length=50)),
                ('Ksd', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FAadanhSachHD',
            fields=[
                ('Sobienban', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Ngaybb', models.DateTimeField()),
                ('Userlap', models.CharField(max_length=50)),
                ('Apdungtungay', models.DateTimeField()),
                ('Tyleckhong', models.IntegerField()),
                ('Dsdangky', models.IntegerField()),
                ('Congnoapdung', models.IntegerField()),
                ('Diengiai', models.CharField(max_length=250)),
                ('Duyet', models.BooleanField()),
                ('Ngayduyet', models.DateTimeField()),
                ('Ghichu', models.TextField(null=True)),
                ('Loaihd', models.CharField(max_length=50)),
                ('Ngayketthuc', models.DateTimeField()),
                ('Makhachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_banhang.aaddskhach')),
            ],
        ),
        migrations.RenameModel(
            old_name='CAadonvinh',
            new_name='CAadonvtinh',
        ),
        migrations.DeleteModel(
            name='AAcdsxuyen',
        ),
        migrations.AlterField(
            model_name='aacdshuyen',
            name='Matinh',
            field=models.ForeignKey(db_column='Matinh', on_delete=django.db.models.deletion.CASCADE, to='api_banhang.aabdstinhthanh'),
        ),
        migrations.RenameModel(
            old_name='AAddsqutang',
            new_name='AAddsquatang',
        ),
        migrations.DeleteModel(
            name='F_AadahnSachHD',
        ),
        migrations.AddField(
            model_name='faadanhsachhd',
            name='Mamonqua',
            field=models.ForeignKey(db_column='Mamonqua', on_delete=django.db.models.deletion.CASCADE, to='api_banhang.aaddsquatang'),
        ),
        migrations.AddField(
            model_name='aacdsxa',
            name='Mahuyen',
            field=models.ForeignKey(db_column='Mahuyen', on_delete=django.db.models.deletion.CASCADE, to='api_banhang.aacdshuyen'),
        ),
        migrations.AlterField(
            model_name='aaddskhach',
            name='Xaphuong',
            field=models.ForeignKey(db_column='Maxa', on_delete=django.db.models.deletion.CASCADE, to='api_banhang.aacdsxa'),
        ),
    ]
