# Generated by Django 3.2.13 on 2025-04-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_banhang', '0002_auto_20250420_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAanhomsp',
            fields=[
                ('ManhomID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Tennhom', models.CharField(max_length=50)),
                ('Ngaytao', models.DateTimeField()),
                ('Usertao', models.CharField(max_length=50)),
                ('Ksd', models.CharField(max_length=50)),
                ('Ghichu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CAbdanhmucnhom',
            fields=[
                ('Manhomsp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Tennhom', models.CharField(max_length=50)),
                ('Ngaytao', models.DateTimeField()),
                ('Usertao', models.CharField(max_length=50)),
                ('Ksd', models.CharField(max_length=50)),
                ('LoainhomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_banhang.caanhomsp')),
            ],
        ),
        migrations.CreateModel(
            name='CACdanhmucsp',
            fields=[
                ('Masp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Tensp', models.CharField(max_length=50)),
                ('Ngaytao', models.DateTimeField()),
                ('Usertao', models.CharField(max_length=50)),
                ('Ksd', models.CharField(max_length=50)),
                ('Hinhanh', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DAaabanggia',
            fields=[
                ('Mabg', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Ngaylap', models.CharField(max_length=50)),
                ('UserID', models.CharField(max_length=50)),
                ('Makhachhang', models.CharField(max_length=50)),
                ('Duyet', models.BooleanField(default=False)),
                ('Ngayapdung', models.DateTimeField()),
                ('Ngayketthuc', models.DateTimeField()),
                ('Userduyet', models.BooleanField(default=False)),
                ('Tenbanggia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DAabadathang',
            fields=[
                ('SoDDH', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('NgayDH', models.DateTimeField()),
                ('UserID', models.CharField(max_length=50)),
                ('Makhachhang', models.CharField(max_length=50)),
                ('Fileinh', models.BinaryField(blank=True, null=True)),
                ('Duyet', models.BooleanField(default=False)),
                ('Ngaycygiaohang', models.DateTimeField()),
                ('Ghichu', models.TextField(blank=True, null=True)),
                ('Mabanggia', models.ForeignKey(db_column='Mabg', on_delete=django.db.models.deletion.CASCADE, to='api_banhang.daaabanggia')),
            ],
        ),
        migrations.CreateModel(
            name='DAabbdathang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Solg', models.IntegerField()),
                ('Dgia', models.IntegerField()),
                ('Giaoc', models.IntegerField()),
                ('Giatt', models.IntegerField()),
                ('Ckkm', models.IntegerField()),
                ('Giamkhac', models.IntegerField()),
                ('Thantientt', models.IntegerField()),
                ('Stt', models.IntegerField()),
                ('Ghi', models.TextField(blank=True, null=True)),
                ('Solggiao', models.IntegerField()),
                ('Thantiengiao', models.IntegerField()),
                ('Ngaygiao', models.IntegerField()),
                ('Masp', models.ForeignKey(db_column='Masp', on_delete=django.db.models.deletion.CASCADE, to='api_banhang.cacdanhmucsp')),
                ('SoDDH', models.ForeignKey(db_column='SoDDH', on_delete=django.db.models.deletion.CASCADE, to='api_banhang.daabadathang')),
            ],
        ),
        migrations.CreateModel(
            name='DAAabanggib',
            fields=[
                ('Masp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Giaoc', models.IntegerField()),
                ('Ckhau', models.IntegerField()),
                ('Giamkhac', models.IntegerField()),
                ('Giatt', models.IntegerField()),
                ('Ghichu', models.TextField(blank=True, null=True)),
                ('Mabg', models.ForeignKey(db_column='Mabg', on_delete=django.db.models.deletion.CASCADE, to='api_banhang.daaabanggia')),
            ],
        ),
        migrations.CreateModel(
            name='CADanhmucPL',
            fields=[
                ('Maphanloai', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Ngaytao', models.DateTimeField()),
                ('Usertao', models.CharField(max_length=50)),
                ('Ksd', models.CharField(max_length=50)),
                ('Dvt', models.CharField(max_length=50)),
                ('Tenphanloai', models.CharField(max_length=50)),
                ('Trongluong', models.IntegerField()),
                ('Manhomsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_banhang.cabdanhmucnhom')),
            ],
        ),
        migrations.AddField(
            model_name='cacdanhmucsp',
            name='MaphanloaiID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_banhang.cadanhmucpl'),
        ),
    ]
