# Generated by Django 3.2.13 on 2025-05-05 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_banhang', '0003_auto_20250421_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abdsnhanvien',
            name='Danghiviec',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abdsnhanvien',
            name='Hinhanh',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abdsnhanvien',
            name='Ksd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abdsnhanvien',
            name='LoaiID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_banhang.aadsvitri'),
        ),
        migrations.AlterField(
            model_name='abdsnhanvien',
            name='MaNPP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='abdsnhanvien',
            name='Pass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='abdsnhanvien',
            name='Sua',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abdsnhanvien',
            name='Them',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abdsnhanvien',
            name='User',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='abdsnhanvien',
            name='Xem',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abdsnhanvien',
            name='Xoa',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
