# Generated by Django 3.2.13 on 2025-05-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_banhang', '0004_auto_20250506_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadsvitri',
            name='Ksd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aadsvitri',
            name='Loaiten',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aadsvitri',
            name='Ngay',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aadsvitri',
            name='Userlap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
