from django.db import models

class AAddsquatang(models.Model):
    Mamonqua = models.CharField(max_length=50, primary_key=True)
    Tenmonqua = models.CharField(max_length=50)
    Ngaytao = models.DateTimeField()
    Giatri = models.IntegerField()
    Hinhanh = models.BinaryField(null=True)
    Doanhsosapdung = models.CharField(max_length=50)
    Ghichu = models.TextField(null=True)

class Aadsvitri(models.Model):
    LoaiID = models.CharField(max_length=50, primary_key=True)
    Loaiten = models.CharField(max_length=50, null=True, blank=True)
    Ngay = models.DateTimeField(null=True, blank=True)
    Userlap = models.CharField(max_length=50, null=True, blank=True)
    Ksd = models.BooleanField(null=True, blank=True)

class Abdsnhanvien(models.Model):
    Manhanvien = models.CharField(max_length=50, primary_key=True)
    Tennhanvien = models.CharField(max_length=50)
    Sodienthoai = models.IntegerField()
    NgayvaoLam = models.DateTimeField()
    LoaiID = models.ForeignKey(Aadsvitri, on_delete=models.SET_NULL, null=True, blank=True)
    User = models.CharField(max_length=50, null=True, blank=True)
    Pass = models.CharField(max_length=50, null=True, blank=True)
    Danghiviec = models.BooleanField(null=True, blank=True)
    Hinhanh = models.BinaryField(null=True, blank=True)
    Xem = models.BooleanField(null=True, blank=True)
    Sua = models.BooleanField(null=True, blank=True)
    Xoa = models.BooleanField(null=True, blank=True)
    Them = models.BooleanField(null=True, blank=True)
    Ksd = models.BooleanField(null=True, blank=True)
    MaNPP = models.CharField(max_length=50, null=True, blank=True)

class AAkhaibaonv(models.Model):
    Maadmin = models.CharField(max_length=50)
    Maquanly = models.CharField(max_length=50)
    Manhanvien = models.ForeignKey(Abdsnhanvien, on_delete=models.SET_NULL, null=True)
    Ngaytao = models.DateTimeField()

class CAadonvtinh(models.Model):
    Madvt = models.CharField(max_length=50, primary_key=True)
    Tendvt = models.CharField(max_length=50)
    Ngaytao = models.DateTimeField()
    Usertao = models.CharField(max_length=50)
    Ksd = models.BooleanField()
    Ghichu = models.TextField(null=True)

class AAbdstinhthanh(models.Model):
    Matinh = models.CharField(max_length=50, primary_key=True)
    Tentinh = models.CharField(max_length=50)
    Danso = models.IntegerField()
    Ngaytao = models.DateTimeField()
    Usertao = models.CharField(max_length=50)
    Dientichkm = models.IntegerField()
    Sohuyen = models.IntegerField()
    Sokilometvc = models.IntegerField()
    kSD = models.BooleanField()

class AAcdshuyen(models.Model):
    Mahuyen = models.CharField(max_length=50, primary_key=True)
    Tenhuyen = models.CharField(max_length=50)
    Danso = models.IntegerField()
    Dientichkm = models.IntegerField()
    Soxa = models.IntegerField()
    Sokilometvc = models.IntegerField()
    Ngaytao = models.DateTimeField()
    Usertao = models.CharField(max_length=50)
    Matinh = models.ForeignKey(AAbdstinhthanh, on_delete=models.CASCADE, db_column='Matinh')
    ksd = models.BooleanField()

class AAcdsxa(models.Model):
    Maxa = models.CharField(max_length=50, primary_key=True)
    Tenxa = models.CharField(max_length=50)
    Danso = models.IntegerField()
    Dientichkm = models.IntegerField()
    Socho = models.IntegerField()
    Sokilometvc = models.IntegerField()
    Ngaytao = models.DateTimeField()
    Usertao = models.CharField(max_length=50)
    Mahuyen = models.ForeignKey(AAcdshuyen, on_delete=models.CASCADE, db_column='Mahuyen')
    Ksd = models.BooleanField()

class AAddskhach(models.Model):
    Makhach = models.CharField(max_length=50, primary_key=True)
    Tenkhach = models.CharField(max_length=50)
    Sodienthoai = models.IntegerField()
    Ngaytao = models.DateTimeField()
    LoaiID = models.ForeignKey(Aadsvitri, on_delete=models.SET_NULL, null=True)
    User = models.CharField(max_length=50)
    Pass = models.CharField(max_length=50)
    Danghi = models.BooleanField()
    Hinhanh = models.BinaryField(null=True)
    Xem = models.BooleanField()
    Sua = models.BooleanField()
    Xoa = models.BooleanField()
    Them = models.BooleanField()
    Ngayvinhhat = models.DateTimeField()
    Diachi = models.CharField(max_length=250)
    Loaiinhinh = models.CharField(max_length=50)
    Nhanvien = models.ForeignKey(Abdsnhanvien, on_delete=models.SET_NULL, null=True)
    Email = models.CharField(max_length=50)
    Sdtzalo = models.CharField(max_length=50)
    Nguoilienhe = models.CharField(max_length=50)
    Xaphuong = models.ForeignKey(AAcdsxa, on_delete=models.CASCADE, db_column='Maxa')
    Ksd = models.BooleanField()

class FAadanhSachHD(models.Model):
    Sobienban = models.CharField(max_length=50, primary_key=True)
    Ngaybb = models.DateTimeField()
    Makhachhang = models.ForeignKey(AAddskhach, on_delete=models.CASCADE)
    Userlap = models.CharField(max_length=50)
    Mamonqua = models.ForeignKey(AAddsquatang, on_delete=models.CASCADE, db_column='Mamonqua')
    Apdungtungay = models.DateTimeField()
    Tyleckhong = models.IntegerField()
    Dsdangky = models.IntegerField()
    Congnoapdung = models.IntegerField()
    Diengiai = models.CharField(max_length=250)
    Duyet = models.BooleanField()
    Ngayduyet = models.DateTimeField()
    Ghichu = models.TextField(null=True)
    Loaihd = models.CharField(max_length=50)
    Ngayketthuc = models.DateTimeField()

class CAanhomsp(models.Model):
    ManhomID = models.CharField(max_length=50, primary_key=True)
    Tennhom = models.CharField(max_length=50)
    Ngaytao = models.DateTimeField()
    Usertao = models.CharField(max_length=50)
    Ksd = models.CharField(max_length=50)
    Ghichu = models.TextField(null=True, blank=True)

class CAbdanhmucnhom(models.Model):
    Manhomsp = models.CharField(max_length=50, primary_key=True)
    Tennhom = models.CharField(max_length=50)
    Ngaytao = models.DateTimeField()
    Usertao = models.CharField(max_length=50)
    Ksd = models.CharField(max_length=50)
    LoainhomID = models.ForeignKey(CAanhomsp, on_delete=models.CASCADE)

class CADanhmucPL(models.Model):
    Maphanloai = models.CharField(max_length=50, primary_key=True)
    Manhomsp = models.ForeignKey(CAbdanhmucnhom, on_delete=models.CASCADE)
    Ngaytao = models.DateTimeField()
    Usertao = models.CharField(max_length=50)
    Ksd = models.CharField(max_length=50)
    Dvt = models.CharField(max_length=50)
    Tenphanloai = models.CharField(max_length=50)
    Trongluong = models.IntegerField()

class CACdanhmucsp(models.Model):
    Masp = models.CharField(max_length=50, primary_key=True)
    Tensp = models.CharField(max_length=50)
    Ngaytao = models.DateTimeField()
    Usertao = models.CharField(max_length=50)
    Ksd = models.CharField(max_length=50)
    MaphanloaiID = models.ForeignKey(CADanhmucPL, on_delete=models.CASCADE)
    Hinhanh = models.BinaryField(null=True, blank=True)

class DAaabanggia(models.Model):
    Mabg = models.CharField(max_length=50, primary_key=True)
    Ngaylap = models.CharField(max_length=50)
    UserID = models.CharField(max_length=50)
    Makhachhang = models.CharField(max_length=50)
    Duyet = models.BooleanField(default=False)
    Ngayapdung = models.DateTimeField()
    Ngayketthuc = models.DateTimeField()
    Userduyet = models.BooleanField(default=False)
    Tenbanggia = models.CharField(max_length=50)

class DAAabanggib(models.Model):
    Mabg = models.ForeignKey(DAaabanggia, on_delete=models.CASCADE, db_column='Mabg')
    Masp = models.CharField(max_length=50, primary_key=True)
    Giaoc = models.IntegerField()
    Ckhau = models.IntegerField()
    Giamkhac = models.IntegerField()
    Giatt = models.IntegerField()
    Ghichu = models.TextField(null=True, blank=True)

class DAabadathang(models.Model):
    SoDDH = models.CharField(max_length=50, primary_key=True)
    NgayDH = models.DateTimeField()
    UserID = models.CharField(max_length=50)
    Makhachhang = models.CharField(max_length=50)
    Mabanggia = models.ForeignKey(DAaabanggia, on_delete=models.CASCADE, db_column='Mabg')
    Fileinh = models.BinaryField(null=True, blank=True)
    Duyet = models.BooleanField(default=False)
    Ngaycygiaohang = models.DateTimeField()
    Ghichu = models.TextField(null=True, blank=True)

class DAabbdathang(models.Model):
    SoDDH = models.ForeignKey(DAabadathang, on_delete=models.CASCADE, db_column='SoDDH')
    Masp = models.ForeignKey(CACdanhmucsp, on_delete=models.CASCADE, db_column='Masp')
    Solg = models.IntegerField()
    Dgia = models.IntegerField()
    Giaoc = models.IntegerField()
    Giatt = models.IntegerField()
    Ckkm = models.IntegerField()
    Giamkhac = models.IntegerField()
    Thantientt = models.IntegerField()
    Stt = models.IntegerField()
    Ghi = models.TextField(null=True, blank=True)
    Solggiao = models.IntegerField()
    Thantiengiao = models.IntegerField()
    Ngaygiao = models.IntegerField()
